#!/usr/bin/env python3.11
"""codegen_vocab.py — generate src/vocab.rs from the canonical Python vocab.py.

The Python tables in ../vocab.py (TAGS, ATTRS, SHARED_STRINGS, UNKNOWN_ID) are
the single source of truth. Never hand-edit src/vocab.rs; re-run this script:

    python3.11 codegen_vocab.py
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent  # the storetle Python package root
sys.path.insert(0, str(SRC))

from storetle import vocab  # noqa: E402

OUT = HERE / "src" / "vocab.rs"


def rust_str(s: str) -> str:
    """Emit a Rust string literal (escaped)."""
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append("\\u{%04x}" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def emit_array(name: str, items) -> str:
    lines = [f"pub static {name}: [&str; {len(items)}] = ["]
    for s in items:
        lines.append(f"    {rust_str(s)},")
    lines.append("];")
    return "\n".join(lines)


def main():
    parts = [
        "// vocab.rs — GENERATED by codegen_vocab.py from ../vocab.py. DO NOT EDIT.",
        "//",
        "// Re-generate with: python3.11 codegen_vocab.py",
        "",
        f"/// Sentinel: tag/attr id not in the known tables (followed by a string ref).",
        f"pub const UNKNOWN_ID: u8 = {vocab.UNKNOWN_ID:#04x};",
        "",
        emit_array("TAGS", vocab.TAGS),
        "",
        emit_array("ATTRS", vocab.ATTRS),
        "",
        emit_array("SHARED_STRINGS", vocab.SHARED_STRINGS),
        "",
    ]
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(
        f"wrote {OUT}: {len(vocab.TAGS)} tags, {len(vocab.ATTRS)} attrs, "
        f"{len(vocab.SHARED_STRINGS)} shared strings, UNKNOWN_ID={vocab.UNKNOWN_ID}"
    )


if __name__ == "__main__":
    main()
